### ISSUE TITLE
IoError(Os { code: 9, kind: Other, message: "Bad file descriptor" }) when saving gif

### ISSUE THREAD

**Issue by Daggy1234** [image-rs/image#1415]
This happens in 
the ImageDecoder when trying to encode_frames

## Expected

Should have encoded file saved to location

## Actual behaviour

throws IoError Bad file descriptor

## Reproduction steps

```rust
use image::gif::{GifDecoder, GifEncoder};
use image::{ImageDecoder, AnimationDecoder};
use std::fs::File;
use std::env;
use std::time::{Duration, Instant};

fn main() {
    env::set_var("RUST_BACKTRACE", "full");
    // Decode a gif into frames
    let mut now = Instant::now();
    let file_in = File::open("./src/p2.gif").expect("No file");
    let mut decoder = GifDecoder::new(file_in).unwrap();
    let frames = decoder.into_frames();
    let frames = frames.collect_frames().expect("error decoding gif");
    println!("{} seconds to encode", now.elapsed().as_secs());
    now = Instant::now();
    // Encode frames into a gif and save to a file
    let file_out = File::open("src/out.gif").expect("some shit");
    let mut encoder = GifEncoder::new(file_out);
    encoder.encode_frames(frames.into_iter()).expect("NO decode");
    println!("{} seconds to save encoded", now.elapsed().as_secs());
}

```
Dependencies:

image="0.23.12"
os: Macos Catalina
rustc 1.48.0 (7eac88abb 2020-11-16)
cargo 1.48.0 (65cbdd2dc 2020-10-14)

Stack trace
```rust

    Finished dev [unoptimized + debuginfo] target(s) in 1.94s
     Running `target/debug/rust-test`
3 seconds to encode
thread 'main' panicked at 'NO decode: IoError(Os { code: 9, kind: Other, message: "Bad file descriptor" })', src/main.rs:20:47
stack backtrace:
   0:        0x103560ad4 - std::backtrace_rs::backtrace::libunwind::trace::h6df1416181381e81
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:        0x103560ad4 - std::backtrace_rs::backtrace::trace_unsynchronized::h792524067a83cded
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:        0x103560ad4 - std::sys_common::backtrace::_print_fmt::he614892186429f3f
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:79
   3:        0x103560ad4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hcfc48256a5ab8835
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:58
   4:        0x103577290 - core::fmt::write::haf3903118f694c48
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/fmt/mod.rs:1080
   5:        0x10355e7d6 - std::io::Write::write_fmt::h7385463ac87804ed
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/io/mod.rs:1516
   6:        0x10356240f - std::sys_common::backtrace::_print::ha64a9740ea6183e6
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:61
   7:        0x10356240f - std::sys_common::backtrace::print::h1fad353b070e1eef
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:48
   8:        0x10356240f - std::panicking::default_hook::{{closure}}::h91bd4c58cf71392b
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:208
   9:        0x1035620dd - std::panicking::default_hook::h7bd29c87df967048
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:227
  10:        0x1035629db - std::panicking::rust_panic_with_hook::hae2b05f08a320721
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:577
  11:        0x10356255b - std::panicking::begin_panic_handler::{{closure}}::h72d68d3a77e0b718
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:484
  12:        0x103560f48 - std::sys_common::backtrace::__rust_end_short_backtrace::h7c5e286792f94edb
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:153
  13:        0x10356251a - rust_begin_unwind
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
  14:        0x10357c2bf - core::panicking::panic_fmt::h1b194bb80d76fb10
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85
  15:        0x10357c1c5 - core::option::expect_none_failed::h75fa4820ade504dc
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/option.rs:1234
  16:        0x1034fe1e6 - core::result::Result<T,E>::expect::h9074dec8dbdf1af4
                               at /Users/jmahavir/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/result.rs:933
  17:        0x103504978 - rust_test::main::h5541390f7c4dfc2e
                               at /Users/jmahavir/code/polaroid/rust-test/src/main.rs:20
  18:        0x1034feb9e - core::ops::function::FnOnce::call_once::h931e6bc3860b57c7
                               at /Users/jmahavir/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:227
  19:        0x1034fce21 - std::sys_common::backtrace::__rust_begin_short_backtrace::h77b5ad6e4b07259e
                               at /Users/jmahavir/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:137
  20:        0x1034f9424 - std::rt::lang_start::{{closure}}::h1225d17551c8f652
                               at /Users/jmahavir/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/rt.rs:66
  21:        0x103562d54 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h4daab3ed47411afb
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ops/function.rs:259
  22:        0x103562d54 - std::panicking::try::do_call::h5f7f7b1d8bd7dc86
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:381
  23:        0x103562d54 - std::panicking::try::h29495f6475fc1ef1
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:345
  24:        0x103562d54 - std::panic::catch_unwind::h1ebce9249c33ec53
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panic.rs:382
  25:        0x103562d54 - std::rt::lang_start_internal::hd38bb63f9540b327
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/rt.rs:51
  26:        0x1034f9401 - std::rt::lang_start::h1ecfab306feaa0b6
                               at /Users/jmahavir/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/rt.rs:65
  27:        0x103504ab2 - _main
```

**Comment by HeroicKatora** [comment]
What makes you think that `image` is causing this error? OS errors are usually returned from the OS and you should generally expect that any IO can fail—disk full, too many open files, etc…—not unwrap it.

**Comment by Daggy1234** [comment]
Well neither of those errors, infact I was able to write new gifs  using the python `PIL` library just fine. I have more than enough space and I also don't think there were too many files

**Comment by HeroicKatora** [comment]
> let file_out = File::open("src/out.gif").expect("some shit");

Here you're opening a file with default access mode for reading but try to write to it. You'll want to call `create` or configure `OpenOptions` instead.

* [`pub fn open<P: AsRef<Path>>(path: P) -> Result<File>`](https://doc.rust-lang.org/stable/std/fs/struct.File.html#method.open)
 Attempts to open a file in read-only mode.

IO errors aren't usually caused at the location that they trigger.
