### ISSUE TITLE
Panic with some TGA files

### ISSUE THREAD

**Issue by gsurrel** [image-rs/image#1420]
This happens in the software:
- https://github.com/qarmin/czkawka/tree/master/czkawka_gui

Link to issue I opened there:
- https://github.com/qarmin/czkawka/issues/237#issuecomment-770440958

## Expected

The thread processing the images panics, which it should not.

## Actual behaviour

The thread panics, preventing the software to continue normally.

## Reproduction steps

Run czkawka_gui (available through cargo install, requires GTK libraries), and scan for "Broken files" in a firectory containing the [following zipped TGA image](https://github.com/image-rs/image/files/5902901/Aurinko_dazzle.tga.zip).

.

**Comment by fintelia** [comment]
Could you capture a backtrace with the line of code where the panic is?

**Comment by qarmin** [comment]
```
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 2', /home/rafal/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/mod.rs:545:31
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:495:5
   1: core::panicking::panic_fmt
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/panicking.rs:92:14
   2: core::panicking::panic_bounds_check
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/panicking.rs:69:5
   3: core::slice::<impl [T]>::swap
             at /home/rafal/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/mod.rs:545:31
   4: image::codecs::tga::decoder::TgaDecoder<R>::reverse_encoding
             at /home/rafal/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.23.12/./src/codecs/tga/decoder.rs:292:21
   5: <image::codecs::tga::decoder::TgaDecoder<R> as image::image::ImageDecoder>::read_image
             at /home/rafal/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.23.12/./src/codecs/tga/decoder.rs:412:9
   6: image::image::decoder_to_vec
             at /home/rafal/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.23.12/./src/image.rs:422:5
   7: image::dynimage::decoder_to_image
             at /home/rafal/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.23.12/./src/dynimage.rs:1105:23
   8: image::dynimage::DynamicImage::from_decoder
             at /home/rafal/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.23.12/./src/dynimage.rs:194:9
   9: image::io::free_functions::load
             at /home/rafal/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.23.12/./src/io/free_functions.rs:73:36
  10: image::io::free_functions::open_impl
             at /home/rafal/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.23.12/./src/io/free_functions.rs:48:5
  11: image::dynimage::open
             at /home/rafal/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.23.12/./src/dynimage.rs:1236:5
  12: image_opening::main
             at ./src/main.rs:86:41
  13: core::ops::function::FnOnce::call_once
             at /home/rafal/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by qarmin** [comment]
More broken files - 
[a.zip](https://github.com/image-rs/image/files/5936964/a.zip)


Only `image::open` is require to crash library
