### ISSUE TITLE
wasm_bindgen Error: Access to forbidden memory address when retrieving address and length of result data

### ISSUE THREAD

**Issue by javadoors** [image-rs/image#1573]
This happens in wasm_bindgen

#[wasm_bindgen]
pub fn super_resolution(image_data: &[u8]) -> Vec<u8> {
  let mut imgbuf: RgbImage  = image::ImageBuffer::new(200, 200);
}
## Expected
The code can run.

## Actual behaviour
/opt/study/wasmedge-nodejs-starter/wasmedge-nodejs-local/pkg/wasmedge_nodejs_starter_lib.js:65
    let b = vm.RunUint8Array('super_resolution', image_data);
               ^
**Error: Access to forbidden memory address when retrieving address and length of result data**
    at module.exports.super_resolution (/opt/study/wasmedge-nodejs-starter/wasmedge-nodejs-local/pkg/wasmedge_nodejs_starter_lib.js:65:16)
    at Object.<anonymous> (/opt/study/wasmedge-nodejs-starter/wasmedge-nodejs-local/node/test.js:19:28)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'Error'
}
## Reproduction steps
https://gitee.com/javadoors/study/blob/master/wasm/wasmedge_nodejs/src/lib.rs
at line:339

**Comment by javadoors** [comment]
Thanks,I will refer to wasm_bindgen document.
