### ISSUE TITLE
Opening broken webp crash with message `thread 'main' panicked at 'index out of bounds:`

### ISSUE THREAD

**Issue by qarmin** [image-rs/image#1612]
Opening this file - [vp8x-rgb23015.webp.zip](https://github.com/image-rs/image/files/7547987/vp8x-rgb23015.webp.zip)
cause this crash
```
Trying to open /home/rafal/Desktop/C/vp8x-rgb23015.webp
thread 'main' panicked at 'index out of bounds: the len is 8100 but the index is 8100', /home/rafal/.cargo/git/checkouts/image-c1c0bf49fde10069/69e686a/./src/codecs/webp/loop_filter.rs:59:47
stack backtrace:
   0: rust_begin_unwind
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:101:14
   2: core::panicking::panic_bounds_check
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:77:5
   3: image::codecs::webp::loop_filter::simple_threshold
   4: image::codecs::webp::loop_filter::should_filter
             at ./.cargo/git/checkouts/image-c1c0bf49fde10069/69e686a/./src/codecs/webp/loop_filter.rs:63:5
   5: image::codecs::webp::loop_filter::subblock_filter
             at ./.cargo/git/checkouts/image-c1c0bf49fde10069/69e686a/./src/codecs/webp/loop_filter.rs:88:8
   6: image::codecs::webp::vp8::Vp8Decoder<R>::loop_filter
             at ./.cargo/git/checkouts/image-c1c0bf49fde10069/69e686a/./src/codecs/webp/vp8.rs:1798:29
   7: image::codecs::webp::vp8::Vp8Decoder<R>::decode_frame
             at ./.cargo/git/checkouts/image-c1c0bf49fde10069/69e686a/./src/codecs/webp/vp8.rs:2057:17
   8: image::codecs::webp::decoder::WebPDecoder<R>::read_frame
             at ./.cargo/git/checkouts/image-c1c0bf49fde10069/69e686a/./src/codecs/webp/decoder.rs:131:21
   9: image::codecs::webp::decoder::WebPDecoder<R>::read_metadata
             at ./.cargo/git/checkouts/image-c1c0bf49fde10069/69e686a/./src/codecs/webp/decoder.rs:142:13
  10: image::codecs::webp::decoder::WebPDecoder<R>::new
             at ./.cargo/git/checkouts/image-c1c0bf49fde10069/69e686a/./src/codecs/webp/decoder.rs:69:9
  11: image::io::free_functions::load_decoder
             at ./.cargo/git/checkouts/image-c1c0bf49fde10069/69e686a/./src/io/free_functions.rs:56:59
  12: image::io::free_functions::load_inner
             at ./.cargo/git/checkouts/image-c1c0bf49fde10069/69e686a/./src/io/free_functions.rs:95:5
  13: image::io::free_functions::load
             at ./.cargo/git/checkouts/image-c1c0bf49fde10069/69e686a/./src/io/free_functions.rs:35:5
  14: image::io::free_functions::open_impl
             at ./.cargo/git/checkouts/image-c1c0bf49fde10069/69e686a/./src/io/free_functions.rs:21:5
  15: image::dynimage::open
             at ./.cargo/git/checkouts/image-c1c0bf49fde10069/69e686a/./src/dynimage.rs:1055:5
  16: image_opening::main
             at ./Projekty/Rust/image_opening/src/main.rs:90:28
  17: core::ops::function::FnOnce::call_once
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Aborted (core dumped)

```

**Comment by tristanphease** [comment]
Ok, the issue is that I forgot some bounds checks in loop filtering :/
Or rather by adding some bounds checks it causes issues in other ways.

**Explanation:**
```
for x in (4usize..luma_xlength-3).step_by(4) {
    for y in 0..luma_ylength {
        let y0 = mby * 16 + y;
        let x0 = mbx * 16 + x;

        loop_filter::subblock_filter(
            hev_threshold, 
            interior_limit, 
            sub_bedge_limit, 
            &mut self.frame.ybuf[..], 
            y0 * luma_w + x0, 
            1
        );
    }
}
```

This subblock filter works on the 8 pixels either side of the 3 edges inside each macroblock
The 4usize..luma_xlength-3 is so if e.g. luma_xlength is 4 it shouldn't loop since there isn't the pixels there to filter on so
 it only iterates for when there is 4 pixels on the right to iterate over.
However what I missed is if luma_xlength is less than 3 then we get a negative number for this range which is a usize and in release mode it overflows so it filters way to the right of the image which causes the error you reported.
**Fix:**
I think the fix is to just add a check to make sure luma_xlength > 3, also should do the same with luma_ylength.

**Comment by tristanphease** [comment]
There's also a luma_xlength-1 for the simple filter but it should be fine since luma_xlength should never be 0 since then the macroblock shouldn't exist.
