### ISSUE TITLE
Debug-mode arithmetic overflow in ICO decoding (found by fuzzer)

### ISSUE THREAD

**Issue by Shnatsel** [image-rs/image#1747]
Decoding a fuzzer-generated file causes integer overflow, which leads to a panic in debug mode.

```
thread '<unnamed>' panicked at 'attempt to add with overflow', image/./src/codecs/ico/decoder.rs:363:31
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f2d93935ffba3ab9d7ccb5300771a2d29b4c8bf3/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/f2d93935ffba3ab9d7ccb5300771a2d29b4c8bf3/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at /rustc/f2d93935ffba3ab9d7ccb5300771a2d29b4c8bf3/library/core/src/panicking.rs:48:5
   3: <image::codecs::ico::decoder::IcoDecoder<R> as image::image::ImageDecoder>::read_image
   4: image::image::decoder_to_vec
   5: image::dynimage::decoder_to_image
   6: <image::io::free_functions::load_inner::LoadVisitor as image::io::free_functions::DecoderVisitor>::visit_decoder
   7: image::io::free_functions::load_decoder
   8: rust_fuzzer_test_input
   9: __rust_try
  10: LLVMFuzzerTestOneInput
  11: _ZN6fuzzer6Fuzzer15ExecuteCallbackEPKhm
  12: _ZN6fuzzer10RunOneTestEPNS_6FuzzerEPKcm
  13: _ZN6fuzzer12FuzzerDriverEPiPPPcPFiPKhmE
  14: main
  15: __libc_start_main
  16: _start
```

This happens on commit 04052e64c9a94606efc8bd3d87d5f3e0f566774e (latest as of this writing)

## Reproduction steps

`cargo +nightly fuzz run fuzzer_script_ico path/to/file`

The file triggering the issue: [crash-981fee302fe0fc543ee48292cc3d6ace7e97e633.ico.gz](https://github.com/image-rs/image/files/9041427/crash-981fee302fe0fc543ee48292cc3d6ace7e97e633.ico.gz)

**Comment by fisherdarling** [comment]
Hi! I'd like to try and tackle this :)
