### ISSUE TITLE
Panic while allocating big vector in fuzzer_script_exr.rs

### ISSUE THREAD

**Issue by anfedotoff** [image-rs/image#1778]
Hi!
We were doing some fuzzing with our tool Sydr and libFuzzer.  We  caught a  panic [here](https://github.com/image-rs/image/blob/master/fuzz/fuzzers/fuzzer_script_exr.rs#L25), trying to allocate a huge vector.

## Expected
I think, if we failed to allocate this we should continue fuzzing. Using [try_reserve](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.try_reserve) doesn't help because, we catch sanitizers error:  `AddressSanitizer: requested allocation size 0xffffffffffffffff`

But maybe it is a bug in parsing image? `decoder.total_bytes()` returns a strange value, it's larger than input file:
[crash-sydr_21c91c10c5bd6a850f36ff6683ce16b4e9089c35_int_overflow_4.txt](https://github.com/image-rs/image/files/9446294/crash-sydr_21c91c10c5bd6a850f36ff6683ce16b4e9089c35_int_overflow_4.txt)

Also, I found some work around [here](https://github.com/image-rs/image/blob/6e0cd31a5287dd589d2e78ae33c1f720c77a6863/fuzz/fuzzers/fuzzer_script_tga.rs#L12).

## Actual behaviour
```
Running: /fuzz/exr-out/crashes/crash-sydr_21c91c10c5bd6a850f36ff6683ce16b4e9089c35_int_overflow_4
thread '<unnamed>' panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:518:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==13== ERROR: libFuzzer: deadly signal
    #0 0x55ee086dba61 in __sanitizer_print_stack_trace /rustc/llvm/src/llvm-project/compiler-rt/lib/asan/asan_stack.cpp:87:3
    #1 0x55ee0a25bd80 in fuzzer::PrintStackTrace() /root/.cargo/registry/src/github.com-1ecc6299db9ec823/libfuzzer-sys-0.3.5/libfuzzer/FuzzerUtil.cpp:210:38
    #2 0x55ee0a26b67a in fuzzer::Fuzzer::CrashCallback() /root/.cargo/registry/src/github.com-1ecc6299db9ec823/libfuzzer-sys-0.3.5/libfuzzer/FuzzerLoop.cpp:233:18
    #3 0x55ee0a26b67a in fuzzer::Fuzzer::CrashCallback() /root/.cargo/registry/src/github.com-1ecc6299db9ec823/libfuzzer-sys-0.3.5/libfuzzer/FuzzerLoop.cpp:228:6
    #4 0x7f240298241f  (/lib/x86_64-linux-gnu/libpthread.so.0+0x1441f) (BuildId: 7b4536f41cdaa5888408e82d0836e33dcf436466)
    #5 0x7f240266a00a in __libc_signal_restore_set /build/glibc-SzIz7B/glibc-2.31/signal/../sysdeps/unix/sysv/linux/internal-signals.h:86:3
    #6 0x7f240266a00a in raise /build/glibc-SzIz7B/glibc-2.31/signal/../sysdeps/unix/sysv/linux/raise.c:48:3
    #7 0x7f2402649858 in abort /build/glibc-SzIz7B/glibc-2.31/stdlib/abort.c:79:7
    #8 0x55ee0a2dca56 in std::sys::unix::abort_internal::he27a37d61b2ed41a /rustc/7480389611f9d04bd34adf41a2b3029be4eb815e/library/std/src/sys/unix/mod.rs:293:14
    #9 0x55ee0864d886 in std::process::abort::hfcb96511de2eae1c /rustc/7480389611f9d04bd34adf41a2b3029be4eb815e/library/std/src/process.rs:2119:5
    #10 0x55ee0a24c8f3 in libfuzzer_sys::initialize::_$u7b$$u7b$closure$u7d$$u7d$::h661ef488c66c237e /root/.cargo/registry/src/github.com-1ecc6299db9ec823/libfuzzer-sys-0.3.5/src/lib.rs:51:9
    #11 0x55ee0a2d1c2c in std::panicking::rust_panic_with_hook::ha5fcab7510d2c291 /rustc/7480389611f9d04bd34adf41a2b3029be4eb815e/library/std/src/panicking.rs:702:17
    #12 0x55ee0a2d1a40 in std::panicking::begin_panic_handler::_$u7b$$u7b$closure$u7d$$u7d$::h1916fdb5e93d55b3 /rustc/7480389611f9d04bd34adf41a2b3029be4eb815e/library/std/src/panicking.rs:586:13
    #13 0x55ee0a2cecab in std::sys_common::backtrace::__rust_end_short_backtrace::h23fd3d7e6530fb89 /rustc/7480389611f9d04bd34adf41a2b3029be4eb815e/library/std/src/sys_common/backtrace.rs:138:18
    #14 0x55ee0a2d17a1 in rust_begin_unwind /rustc/7480389611f9d04bd34adf41a2b3029be4eb815e/library/std/src/panicking.rs:584:5
    #15 0x55ee0864f022 in core::panicking::panic_fmt::he089491c0abfaeea /rustc/7480389611f9d04bd34adf41a2b3029be4eb815e/library/core/src/panicking.rs:142:14
    #16 0x55ee0a318ea8 in alloc::raw_vec::capacity_overflow::h6dc102efaeec08ef /rustc/7480389611f9d04bd34adf41a2b3029be4eb815e/library/alloc/src/raw_vec.rs:518:5
    #17 0x55ee089b2d80 in alloc::raw_vec::RawVec$LT$T$C$A$GT$::allocate_in::h82c6e400ef087b67 /rustc/7480389611f9d04bd34adf41a2b3029be4eb815e/library/alloc/src/raw_vec.rs:178:27
    #18 0x55ee089b2d80 in alloc::raw_vec::RawVec$LT$T$C$A$GT$::with_capacity_zeroed_in::hdc3506dd9488fa82 /rustc/7480389611f9d04bd34adf41a2b3029be4eb815e/library/alloc/src/vec/spec_from_elem.rs:52:31
    #19 0x55ee089b2d80 in _$LT$u8$u20$as$u20$alloc..vec..spec_from_elem..SpecFromElem$GT$::from_elem::ha9817e867545a7ba /rustc/7480389611f9d04bd34adf41a2b3029be4eb815e/library/alloc/src/vec/spec_from_elem.rs:52:31
    #20 0x55ee089b2d80 in alloc::vec::from_elem::hd2523a4b60256a33 /rustc/7480389611f9d04bd34adf41a2b3029be4eb815e/library/alloc/src/vec/mod.rs:2458:5
    #21 0x55ee089b2d80 in fuzzer_script_exr::roundtrip::read_as_rgba_byte_image::h86f85198935ca718 /image/fuzz/fuzzers/fuzzer_script_exr.rs:25:26
    #22 0x55ee089b1184 in fuzzer_script_exr::roundtrip::h286957c8ef1d1541 /image/fuzz/fuzzers/fuzzer_script_exr.rs:43:25
    #23 0x55ee089b456f in rust_fuzzer_test_input /image/fuzz/fuzzers/fuzzer_script_exr.rs:56:16
    #24 0x55ee0a24c957 in __rust_try libfuzzer_sys.8fd6e53f-cgu.0
    #25 0x55ee0a24c1e3 in std::panicking::try::h6c266d8655016d6a /rustc/7480389611f9d04bd34adf41a2b3029be4eb815e/library/std/src/panicking.rs:456:19
    #26 0x55ee0a24c1e3 in std::panic::catch_unwind::hd398871bcb2aad9c /rustc/7480389611f9d04bd34adf41a2b3029be4eb815e/library/std/src/panic.rs:137:14
    #27 0x55ee0a24c1e3 in LLVMFuzzerTestOneInput /root/.cargo/registry/src/github.com-1ecc6299db9ec823/libfuzzer-sys-0.3.5/src/lib.rs:25:22
    #28 0x55ee0a26bbbc in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /root/.cargo/registry/src/github.com-1ecc6299db9ec823/libfuzzer-sys-0.3.5/libfuzzer/FuzzerLoop.cpp:611:17
    #29 0x55ee0a24ffd9 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /root/.cargo/registry/src/github.com-1ecc6299db9ec823/libfuzzer-sys-0.3.5/libfuzzer/FuzzerDriver.cpp:324:21
    #30 0x55ee0a259db2 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /root/.cargo/registry/src/github.com-1ecc6299db9ec823/libfuzzer-sys-0.3.5/libfuzzer/FuzzerDriver.cpp:860:19
    #31 0x55ee0864f3f6 in main /root/.cargo/registry/src/github.com-1ecc6299db9ec823/libfuzzer-sys-0.3.5/libfuzzer/FuzzerMain.cpp:20:30
    #32 0x7f240264b082 in __libc_start_main /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:308:16
    #33 0x55ee0864f59d in _start (/fuzzer_script_exr+0xea859d) (BuildId: eff94fdb28d6a1f58bc390b47d2ae6edf1ffe582)
```
## Reproduction steps

    $ cargo +nightly fuzz build -O

    $ ./target/x86_64-unknown-linux-gnu/release/fuzzer_script_exr crash-sydr_21c91c10c5bd6a850f36ff6683ce16b4e9089c35_int_overflow_4.txt

**Comment by anfedotoff** [comment]
Fixed by #1781
