### ISSUE TITLE
'attempt to add with overflow' in webp

### ISSUE THREAD

**Issue by alexanderkjall** [image-rs/image#1916]
This happens in image::codecs::webp::lossless::LosslessDecoder<R>::read_huffman_code_lengths

## Expected

A Result object

## Actual behaviour

backtrace output:

```
thread 'main' panicked at 'attempt to add with overflow', /home/capitol/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.24.6/./src/codecs/webp/lossless.rs:438:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
   2: core::panicking::panic
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:114:5
   3: image::codecs::webp::lossless::LosslessDecoder<R>::read_huffman_code_lengths
             at /home/capitol/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.24.6/src/codecs/webp/lossless.rs:438:13
   4: image::codecs::webp::lossless::LosslessDecoder<R>::read_huffman_code
             at /home/capitol/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.24.6/src/codecs/webp/lossless.rs:422:17
   5: image::codecs::webp::lossless::LosslessDecoder<R>::read_huffman_codes
             at /home/capitol/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.24.6/src/codecs/webp/lossless.rs:366:28
   6: image::codecs::webp::lossless::LosslessDecoder<R>::decode_image_stream
             at /home/capitol/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.24.6/src/codecs/webp/lossless.rs:223:28
   7: image::codecs::webp::lossless::LosslessDecoder<R>::decode_frame
             at /home/capitol/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.24.6/src/codecs/webp/lossless.rs:160:24
   8: image::codecs::webp::decoder::WebPDecoder<R>::read_frame
             at /home/capitol/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.24.6/src/codecs/webp/decoder.rs:172:29
   9: image::codecs::webp::decoder::WebPDecoder<R>::read_data
             at /home/capitol/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.24.6/src/codecs/webp/decoder.rs:193:21
  10: image::codecs::webp::decoder::WebPDecoder<R>::new
             at /home/capitol/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.24.6/src/codecs/webp/decoder.rs:136:9
  11: image::io::free_functions::load_decoder
             at /home/capitol/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.24.6/src/io/free_functions.rs:63:59
  12: image::io::free_functions::load_inner
             at /home/capitol/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.24.6/src/io/free_functions.rs:113:5
  13: image::io::free_functions::load
             at /home/capitol/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.24.6/src/io/free_functions.rs:37:5
  14: image::dynimage::load_from_memory_with_format
             at /home/capitol/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.24.6/src/dynimage.rs:1215:5
  15: image::dynimage::load_from_memory
             at /home/capitol/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.24.6/src/dynimage.rs:1200:5
  16: image_reproduce::main
             at ./src/main.rs:29:13
  17: core::ops::function::FnOnce::call_once
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

## Reproduction steps

```
fn main() {
    let data = vec![0x52, 0x49, 0x46, 0x46, 0xaf, 0x37, 0x80, 0x47, 0x57, 0x45, 0x42, 0x50,
  0x56, 0x50, 0x38, 0x4c, 0x20, 0x00, 0xda, 0x2f, 0x2f, 0x2f, 0xae, 0x3e,
  0x00, 0x98, 0xef, 0xff, 0xff, 0x00, 0x00, 0xff, 0xff, 0xff, 0xfa, 0xfb,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x2f, 0x2f, 0x2f, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x4c,
  0x20, 0x00, 0xda, 0x2f, 0xa4, 0xe6, 0xff, 0xff, 0x00, 0x00, 0x00, 0x08,
  0x00, 0x00, 0x04, 0x2f, 0x2f, 0xe4, 0xd2, 0xff, 0xff, 0x2f, 0x2f, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x84, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbe, 0xc6, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0xff, 0xff, 0xcc, 0x44, 0x00, 0x02, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0xa0, 0x4a, 0x31, 0x39, 0x61, 0x61, 0x61, 0xe0, 0xf8,
  0xff, 0xff, 0x00, 0x00, 0x00, 0x0a, 0x00, 0xd6, 0xfc, 0xff, 0xff, 0x32,
  0x31, 0xff];

    let _ = image::load_from_memory(&data);
}
```

**Comment by Shnatsel** [comment]
This is fixed in the  `next-version-0.25` branch that switches to the `image-webp` crate for WebP decoding.
