### ISSUE TITLE
new test failure on 32-bit x86 (i686) in image v0.24.8 compared to v0.24.7

### ISSUE THREAD

**Issue by decathorpe** [image-rs/image#2097]
I'm responsible for building the packages for the image crate for Fedora Linux, and I noticed a test failure that is new in image v0.24.8.

The failing test is `bad_gif_oom` from the `tests/regression.rs` file:

```
failures:
---- bad_gif_oom stdout ----
thread 'bad_gif_oom' panicked at tests/regression.rs:77:5:
assertion failed: matches!(error, image :: ImageError :: Limits(_)) |
    matches!(error, image :: ImageError :: Unsupported(_))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
failures:
    bad_gif_oom
```

i686 is the only 32-bit architecture we still (partially) support, so I suspect this as a likely cause of the issue. This test passes on all other architectures we support (x86_64, aarch64, powerpc64le, s390x).

Test environment:

- Fedora Rawhide
- Rust 1.75.0
- on i686-unknown-linux-gnu

**Comment by fintelia** [comment]
I was able to replicate this with cargo-cross which gives a backtrace:

```bash
     Running tests/regression.rs (/target/i686-unknown-linux-gnu/debug/deps/regression-1c763a8cbbe3a030)

running 1 test
test bad_gif_oom ... FAILED

failures:

---- bad_gif_oom stdout ----
thread 'bad_gif_oom' panicked at /home/jonathan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gif-0.12.0/src/reader/mod.rs:404:9:
attempt to multiply with overflow
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d86d65bbc19b928387f68427fcc3a0da498d8a19/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/d86d65bbc19b928387f68427fcc3a0da498d8a19/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /rustc/d86d65bbc19b928387f68427fcc3a0da498d8a19/library/core/src/panicking.rs:144:5
   3: gif::reader::Decoder<R>::buffer_size
             at /home/jonathan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gif-0.12.0/src/reader/mod.rs:404:9
   4: <image::codecs::gif::GifDecoder<R> as image::image::ImageDecoder>::read_image
             at ./src/codecs/gif.rs:180:31
   5: image::image::decoder_to_vec
             at ./src/image.rs:721:5
   6: image::dynimage::decoder_to_image
             at ./src/dynimage.rs:1054:23
   7: image::dynimage::DynamicImage::from_decoder
             at ./src/dynimage.rs:193:9
   8: <image::io::free_functions::load_inner::LoadVisitor as image::io::free_functions::DecoderVisitor>::visit_decoder
             at ./src/io/free_functions.rs:109:13
   9: image::io::free_functions::load_decoder
             at ./src/io/free_functions.rs:59:36
  10: image::io::free_functions::load_inner
             at ./src/io/free_functions.rs:113:5
  11: image::io::free_functions::load
             at ./src/io/free_functions.rs:37:5
  12: image::dynimage::load_from_memory_with_format
             at ./src/dynimage.rs:1234:5
  13: image::dynimage::load_from_memory
             at ./src/dynimage.rs:1219:5
  14: regression::bad_gif_oom
             at ./tests/regression.rs:75:17
  15: regression::bad_gif_oom::{{closure}}
             at ./tests/regression.rs:64:17
  16: core::ops::function::FnOnce::call_once
             at /rustc/d86d65bbc19b928387f68427fcc3a0da498d8a19/library/core/src/ops/function.rs:250:5
  17: core::ops::function::FnOnce::call_once
             at /rustc/d86d65bbc19b928387f68427fcc3a0da498d8a19/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by decathorpe** [comment]
Thank you for addressing this so quickly!

Are there plans to publish a new release soon-ish or should I backport the 32-bit and big-endian specific patches for now?

**Comment by fintelia** [comment]
Hoping to get a followup release out relatively soon, but might end up being a week or two
