### ISSUE TITLE
Image resampling results in "arithmetic operation overflowed"

### ISSUE THREAD

**Issue by palfrey** [image-rs/image#543]
Using the code at https://gist.github.com/palfrey/c140beb4c55b279de0af2a76cc5984cd and the test image in the comment of the gist, I can get the below. This is because the height of the image is 0. I would submit a PR with a non-panic error for this, but that would change the API for "resize" which currently always wants to spit out an `ImageBuffer` not a variant of `Result<ImageBuffer>`. Any thoughts?

```
     Running `target/debug/break-image 49581ca0-2bf2-11e6-9b8e-f3964caf8f5f.png`
thread '<main>' panicked at 'arithmetic operation overflowed', /home/palfrey/.cargo/git/checkouts/image-dd026f1f3796b42b/master/./src/imageops/sample.rs:255
stack backtrace:
   1:     0x5651c9395e60 - sys::backtrace::tracing::imp::write::h3675b4f0ca767761Xcv
   2:     0x5651c939874b - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44519
   3:     0x5651c93983b8 - panicking::default_handler::h18faf4fbd296d909lSz
   4:     0x5651c938eedc - sys_common::unwind::begin_unwind_inner::hfb5d07d6e405c6bbg1t
   5:     0x5651c938f328 - sys_common::unwind::begin_unwind_fmt::h8b491a76ae84af35m0t
   6:     0x5651c93952d1 - rust_begin_unwind
   7:     0x5651c93c79cf - panicking::panic_fmt::h98b8cbb286f5298alcM
   8:     0x5651c93c7ca8 - panicking::panic::h4265c0105caa1121SaM
   9:     0x5651c91e5559 - imageops::sample::vertical_sample::h5502002918980303495
                        at /home/palfrey/.cargo/git/checkouts/image-dd026f1f3796b42b/master/./src/imageops/sample.rs:255
  10:     0x5651c91e4e1c - imageops::sample::resize::h5744337326229085325
                        at /home/palfrey/.cargo/git/checkouts/image-dd026f1f3796b42b/master/./src/imageops/sample.rs:396
  11:     0x5651c91e31c4 - main::hf0ab3c41b92c9958jaa
                        at src/main.rs:7
  12:     0x5651c9398014 - sys_common::unwind::try::try_fn::h14622312129452522850
  13:     0x5651c939525b - __rust_try
  14:     0x5651c9397aab - rt::lang_start::h0ba42f7a8c46a626rKz
  15:     0x5651c91e8cb9 - main
  16:     0x7eff5d05082f - __libc_start_main
  17:     0x5651c91e2fd8 - _start
  18:                0x0 - <unknown>
```

**Comment by 197g** [comment]
This is no longer the case. Zero-sized dimensions have tests and overflows were addressed some time ago. This must have slipped the cracks in being open. It now produces an explicit DimensionError instead of panics. As to the test, it detects the input file as being faulty as 0 is not an allowed dimension for `png`—slightly unfortunate for a reproduction but correct as per specification.
