### ISSUE TITLE
wasm32-unknown-emscripten target not working

### ISSUE THREAD

**Issue by semtexzv** [image-rs/image#817]
Package can't be compiled for "wasm32-unknown-unknown" target. Even compiling the tests fails with "corrupted double-linked list" error during linking using llc. 

Command to reproduce: 
`cargo web test --target=wasm32-unknown-emscripten`

This is probably caused by some low-level bit manipulation code somewhere in the library.

**Comment by tomaka** [comment]
What is the error message that you're getting?

**Comment by HeroicKatora** [comment]
What does `cargo web test` do, it is not a standard command.

**Comment by tomaka** [comment]
> Multiple ones,
> `corrupted double-linked list`
> `corrupted size vs. prev_size`
> `double free or corruption (!prev)`
> 
> Seems there is some kind of memory access pattern in `gray_to_luma8` function, that confuses some tool in emscripten toolchain. #818 seems to get the crate compiling on this target.

Can you paste the exact message? We have no idea what produces these messages.

**Comment by philipc** [comment]
https://travis-ci.org/stevebob/gfx/jobs/429755777 has a failure message from running `docker exec -it emscripten cargo test --all --target=asmjs-unknown-emscripten`:
```
*** Error in `/emsdk_portable/llvm/clang/bin/llc': corrupted double-linked list: 0x0000000003148920 ***
*** Error in `/emsdk_portable/llvm/clang/bin/llc': corrupted double-linked list: 0x0000000003f6c780 ***
```

[cargo-web](https://github.com/koute/cargo-web) is a cargo subcommand that makes it easy to build and run for emscripten. I've run this a few times though, and the tests have always compiled successfully. I tried both asmjs and wasm32.

@semtexzv #818 isn't an appropriate fix. Why do you think low level bit manipulation is the problem? Is this a known problem with emscripten? Why would this cause errors in `llc`? Do you have any links with info about this?

**Comment by semtexzv** [comment]
Running "cargo test --target=asmjs-unknown-emscripten" 
results in following error:
```
... Multiple repeated warnings like this
WARNING:root:object /tmp/emscripten_temp_zkyi_kyn_archive_contents/compiler_builtins-eb5df2804a31c9b8.compiler_builtins.22h4jw28-cgu.8.rcgu.bc.z is not valid according to llvm-nm, cannot link
WARNING:root:object /tmp/emscripten_temp_zkyi_kyn_archive_contents/compiler_builtins-eb5df2804a31c9b8.compiler_builtins.22h4jw28-cgu.9.rcgu.bc.z is not valid according to llvm-nm, cannot link
          corrupted double-linked list                                                                                                                                                         
          Traceback (most recent call last):                                                                                                                                                   
            File "/home/semtexzv/emsdk/emscripten/1.38.12/emcc.py", line 3062, in <module>                                                                                                     
              sys.exit(run())                                                                                                                                                                  
            File "/home/semtexzv/emsdk/emscripten/1.38.12/emcc.py", line 1778, in run                                                                                                          
              final = shared.Building.emscripten(final, append_ext=False, extra_args=extra_args)                                                                                               
            File "/home/semtexzv/emsdk/emscripten/1.38.12/tools/shared.py", line 2268, in emscripten                                                                                           
              emscripten._main(cmdline)                                                                                                                                                        
            File "/home/semtexzv/emsdk/emscripten/1.38.12/emscripten.py", line 2228, in _main                                                                                                  
              return temp_files.run_and_clean(lambda: main(                                                                                                                                    
            File "/home/semtexzv/emsdk/emscripten/1.38.12/tools/tempfiles.py", line 93, in run_and_clean                                                                                       
              return func()                                                                                                                                                                    
            File "/home/semtexzv/emsdk/emscripten/1.38.12/emscripten.py", line 2233, in <lambda>                                                                                               
              DEBUG=DEBUG,                                                                                                                                                                     
            File "/home/semtexzv/emsdk/emscripten/1.38.12/emscripten.py", line 2159, in main                                                                                                   
              temp_files=temp_files, DEBUG=DEBUG)                                                                                                                                              
            File "/home/semtexzv/emsdk/emscripten/1.38.12/emscripten.py", line 81, in emscript                                                                                                 
              backend_output = compile_js(infile, temp_files, DEBUG)                                                                                                                           
            File "/home/semtexzv/emsdk/emscripten/1.38.12/emscripten.py", line 110, in compile_js                                                                                              
              jsrun.timeout_run(subprocess.Popen(backend_args, stdout=subprocess.PIPE, universal_newlines=True), note_args=backend_args)                                                       
            File "/home/semtexzv/emsdk/emscripten/1.38.12/tools/jsrun.py", line 20, in timeout_run                                                                                             
              raise Exception('Subprocess "' + ' '.join(note_args) + '" failed with exit code ' + str(proc.returncode) + '!')                                                                  
          Exception: Subprocess "/home/semtexzv/emsdk/clang/e1.38.12_64bit/llc /tmp/tmpv0m12f1v/scaledown-3ad8c81761a28695.bc -march=js -filetype=asm -o /tmp/tmpliuka_l0.4.js -emscripten-stack-size=5242880 -O0 -emscripten-assertions=1 -emscripten-no-aliasing-function-pointers -emscripten-global-base=8 -enable-emscripten-cpp-exceptions -emscripten-no-exit-runtime" failed with exit code -6!
```

Running this command on https://github.com/PistonDevelopers/image/pull/818 correctly builds the crate and generates .js files for tests, even though cargo can't run these on it's own.

The result is the same when running  "cargo test --target=asmjs-unknown-emscripten" 

@philipc I know it isn't an appropriate fix, but at least crate is compilling, and we know where the issue is.

**Comment by tomaka** [comment]
https://github.com/rust-lang/rust/issues/54312

**Comment by philipc** [comment]
No, we don't know where issue is, because I could run the test successfully. However, updating my rust from 1.28.0 to 1.29.1 caused the problem to start occurring. Can you try rust 1.28?

I think this needs to be fixed in rust, not by rewriting `gray_to_luma8`. Even if the problem can be worked around by rewriting `gray_to_luma8`, I can't rewrite it without knowing what the problem is that I'm meant to be avoiding. That's why I asked for more info about why you think it is due to low level bit manipulation.

Also, this kind of problem has happened before for gfx: https://github.com/rust-lang/rust/issues/47023

**Comment by acidicX** [comment]
I can compile it with 1.35 nightly.

**Comment by semtexzv** [comment]
Solved a long time ago, this issue was forgotten. Closing.
